name: typescript-axios
on:
  push:
    branches:
    - main
    paths:
    - 'zerotierone-openapi.yaml'
  workflow_dispatch:
jobs:
  main:
    name: Generate, build and publish
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.*
        registry-url: 'https://registry.npmjs.org'
    
    - name: Setup openapi-generator-cli
      run: |
        npm install @openapitools/openapi-generator-cli -g
        
    - name: Generate
      run: |
        npx openapi-generator-cli generate \
          -i zerotierone-openapi.yaml \
          -g typescript-axios \
          -o zerotierone-api-ts-axios \
          --additional-properties=npmName=zerotierone-api-ts-axios \
          --git-user-id JohnGuan \
          --git-repo-id zerotierone-openapi
          
        cat << EOF | cat - zerotierone-api-ts-axios/README.md > temp && mv temp zerotierone-api-ts-axios/README.md
        > 📄 This document is auto-generated. For detailed information, please refer to the [GitHub repo](https://github.com/JohnGuan/zerotierone-openapi).

        EOF
        
    - name: Build
      run: |
        npm install
        npm run build
      working-directory: zerotierone-api-ts-axios
    
    - name: Publish
      run: |
        npm publish
      working-directory: zerotierone-api-ts-axios
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        

      
