on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  generate:
    name: Generate npm package from OpenAPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Generate
      uses: kpurdon/openapi-generator-action@v0.0.3
      with:
        args: "generate -i zerotierone-openapi.yaml -g typescript-axios -o zerotierone-api-ts-axios --additional-properties=npmName=johnguan/zerotierone-api-ts-axios"
        
  build:
    name: Build npm package
    needs: [generate]
    runs-on: ubuntu-18.04
    steps:
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: cd zerotierone-api-ts-axios
    - run: npm install
    - run: npm run build

  publish:
    name: Publish npm package
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: cd zerotierone-api-ts-axios
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        

      
