on:
  push:
    branches:
    - main
    paths:
    - 'zerotierone-openapi.yaml'
  workflow_dispatch:
jobs:
  main:
    name: Generate, build and publish
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Generate
      uses: kpurdon/openapi-generator-action@v0.0.3
      with:
        args: "generate -i zerotierone-openapi.yaml -g typescript-axios -o zerotierone-api-ts-axios --additional-properties=npmName=johnguan/zerotierone-api-ts-axios"
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        cd zerotierone-api-ts-axios
        sudo npm install
        sudo npm run build
    
    - name: Publish
      run: |
        cd zerotierone-api-ts-axios
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        

      
